In [1]:
# Import standard packages
import numpy as np
import pandas as pd
import itertools
import os
import pywt 

# Import plotting libraries
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
import pandas as pd
data_df=pd.read_csv(r'D:\\1.5inch Pump Data\\With Vibration Sensor Test\\01_P2_20_100-50_Good Diaphragm.csv')

In [3]:
data_df.head(2)

,Time,P2-Cycle-detect,P2-CPM,Left-Vibration-Data,Right-Vibration-Data,P2-Air Supply Pressure,P2-Discharge Flowrate,P2-Air Supply FLowrate
0,2024-09-17 10:30:43.619,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2024-09-17 10:30:43.621,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [4]:
q=pywt.Wavelet('db3')
print(q)

Wavelet db3
  Family name:    Daubechies
  Short name:     db
  Filters length: 6
  Orthogonal:     True
  Biorthogonal:   True
  Symmetry:       asymmetric
  DWT:            True
  CWT:            False


In [10]:
level=2

In [12]:
# Define the time interval for slicing
start_time = data_df.index[0]
end_time = data_df.index[-1]
time_interval = 2000

stddev = [[] for _ in range(level)]
mean = [[] for _ in range(level)]
current_time = start_time
while current_time <= end_time:

    next_time = current_time + time_interval

    # Slice the DataFrame based on the specified time range
    sliced_df = data_df.loc[(data_df.index >= current_time) & (data_df.index <= next_time)]
    
    n = len(sliced_df)
    if n > 0:
        coeffs=pywt.wavedec(sliced_df['P2-Air Supply Pressure'],'db2',level=level,mode='symmetric')
        reconstructed_details = []
        for i in range(0, level+1):
            coeffs_copy = [np.zeros_like(c) for c in coeffs]
            coeffs_copy[i] = coeffs[i]
            reconstructed_detail = pywt.waverec(coeffs_copy, 'db2', mode='symmetric')
            reconstructed_details.append(reconstructed_detail)
        for decom_iter in range(1, level+1):
            decomposed_data_set = reconstructed_details[decom_iter]
            mean[decom_iter - 1].append(np.mean(decomposed_data_set))
            stddev[decom_iter-1].append(np.std(decomposed_data_set))
    else:
        pass
    current_time = next_time

In [50]:
mean_dic = {}
stadev_dic = {}
for lsindex in range(0,len(mean)):
    mean_dic['mean_{}'.format(lsindex+1)] = pd.DataFrame(mean[lsindex])
for lsindex in range(0,len(stddev)):
    stadev_dic['stddev_{}'.format(lsindex+1)] = pd.DataFrame(stddev[lsindex])

In [51]:
stadev_dic['stddev_1'].head()

,0
0,1.192377
1,2.217644
2,2.242144
3,2.222732
4,2.219450


In [39]:
mean_df

,mean_0,mean_1
0,-0.000860,-3.996516e-04
1,-0.000301,-9.230982e-05
2,-0.000302,2.299770e-04
3,0.000419,-7.472521e-06
4,-0.001290,1.525139e-03
...,...,...
420,-0.001821,1.394147e-03
421,0.000243,-1.389252e-04
422,0.001947,1.945323e-04
423,0.000582,-4.416868e-04


In [15]:
stddev

[[1.1923768627322056,
  2.2176437097302806,
  2.2421442610669073,
  2.222731793364374,
  2.219450303552364,
  2.207116534718164,
  2.211310462489302,
  2.197232553193845,
  2.283163315554865,
  2.220387898941646,
  2.2439736309902774,
  2.206345112320919,
  2.2299360211802206,
  2.229961946536402,
  2.2403689236245152,
  2.2136987372167596,
  2.247510995659504,
  2.1986960614081292,
  2.2536863313909725,
  2.2272978942701607,
  2.2488175554539254,
  2.2941670167835184,
  2.224854464915753,
  2.2594913821490827,
  2.2400655680607664,
  2.272237511114832,
  2.237389542633592,
  2.2342881098230754,
  2.246252299312191,
  2.2742372482665663,
  2.226316830134194,
  2.337788464552505,
  1.9911418790441155,
  2.2288336030143094,
  2.1538088919108995,
  2.096579442909894,
  1.6842912185628764,
  1.5940789912592976,
  1.7135606669921062,
  1.6122744056945935,
  1.944633579513221,
  1.7856472840610755,
  1.8543238930357386,
  1.7635134505332588,
  2.0267673664777837,
  2.0496885482756917,
  1.72

In [7]:
coeffs=pywt.wavedec(data_df['P2-Air Supply Pressure'],'db2',level=level,mode='symmetric')
reconstructed_details = []
for i in range(0, level+1):
    coeffs_copy = [np.zeros_like(c) for c in coeffs]
    coeffs_copy[i] = coeffs[i]
    reconstructed_detail = pywt.waverec(coeffs_copy, 'db2', mode='symmetric')
    reconstructed_details.append(reconstructed_detail)
for decom_iter in range(1, level+1):
    decomposed_data_set = reconstructed_details[decom_iter]
    mean[decom_iter - 1].append(np.mean(decomposed_data_set))
    stddev[decom_iter-1].append(np.std(decomposed_data_set))

In [8]:
reconstructed_details

[array([-1.16149374, -1.44491789,  3.7914011 , ..., 13.99061231,
        14.00535302, 14.01377574]),
 array([ 1.16149374,  1.44491789, -3.14981928, ..., -0.0182105 ,
         0.0041648 ,  0.01649265]),
 array([ 0.        ,  0.        , -0.64158183, ..., -0.01989041,
         0.01315533, -0.00759523])]

In [9]:
mean

[[-1.6838353453337141e-06], [2.0865951267395404e-19]]

In [4]:
import pywt
coeffs = pywt.wavedec([1,2,3,4,5,6,7,8], 'db1', level=2)
a=pywt.waverec(coeffs, 'db1')


In [6]:
a

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [5]:
coeffs

[array([ 5., 13.]),
 array([-2., -2.]),
 array([-0.70710678, -0.70710678, -0.70710678, -0.70710678])]

In [ ]:
stddev

In [ ]:
mean

In [ ]:
reconstructed_details

In [ ]:
coeffs